export const ERAS = [
  { id: 'postwar', label: 'Post-War Order', years: [1945, 1955], color: '#4a6fa5' },
  { id: 'coldwar', label: 'Cold War Peak', years: [1955, 1975], color: '#8b1a1a' },
  { id: 'detente', label: 'Détente & Shocks', years: [1975, 1991], color: '#c9a050' },
  { id: 'unipolar', label: 'Unipolar Moment', years: [1991, 2008], color: '#2a5c45' },
  { id: 'multipolar', label: 'Multipolar Fracture', years: [2008, 2026], color: '#6b3fa0' },
];

export const START_YEAR = 1945;
export const END_YEAR = 2026;

export const EVENTS = [
  // --- POST-WAR ORDER ---
  { id: 'e1', year: 1944, type: 'trade', title: 'Bretton Woods Conference', era: 'postwar',
    detail: 'The Bretton Woods Conference established the post-war international monetary order, pegging 44 nations\' currencies to the USD and creating the IMF and World Bank. The dollar became the world\'s reserve currency, underwritten by the promise of gold convertibility at $35/oz. This gave the United States unprecedented structural power over global trade financing for the next 27 years. The British delegation, led by Keynes, pushed for a neutral international currency (bancor) but lost — setting the stage for the "exorbitant privilege" debate that continues today.' },
  { id: 'e2', year: 1945, type: 'conflict', title: 'Hiroshima & Nagasaki / V-J Day', era: 'postwar',
    detail: 'The atomic bombings of Hiroshima (Aug 6) and Nagasaki (Aug 9) ended the Pacific War with Japan\'s surrender on Aug 15. The decision revealed that the United States had achieved a decisive technological supremacy that would define great-power deterrence for the entire Cold War era. The "nuclear umbrella" became America\'s core security export to allies — fundamentally reshaping the calculus of trade, alliance, and territorial conflict globally.' },
  { id: 'e3', year: 1947, type: 'trade', title: 'GATT & Marshall Plan', era: 'postwar',
    detail: 'The General Agreement on Tariffs and Trade (GATT) established multilateral trade rules for 23 nations, beginning a 50-year liberalization process. Simultaneously, the Marshall Plan ($13.3B ≈ $150B today) rebuilt Western Europe — but critically, it was designed to create export markets for American goods and foreclose Soviet expansion. Aid recipients were required to buy American products, cementing the dollar\'s centrality. Together, GATT and Marshall created an interlocking web: security guarantees for market access.' },
  { id: 'e4', year: 1947, type: 'conflict', title: 'Truman Doctrine / Containment', era: 'postwar',
    detail: 'President Truman\'s address to Congress on March 12, 1947 committed the United States to "support free peoples who are resisting attempted subjugation by armed minorities or by outside pressures" — initially Greece and Turkey. George Kennan\'s "Long Telegram" and subsequent "X Article" had laid the strategic framework: contain Soviet expansion without direct confrontation. This doctrine structured American foreign policy for 44 years and justified interventions on every inhabited continent.' },
  { id: 'e5', year: 1949, type: 'conflict', title: 'NATO Founded / Soviet A-Bomb', era: 'postwar',
    detail: 'NATO (April 1949) formalized the US security guarantee to Western Europe — an unprecedented peacetime collective defense pact. Five months later, the Soviet Union detonated its first nuclear device (Joe-1), shattering the American monopoly. The combination accelerated an arms race, made Europe permanently divided, and forced both superpowers into a logic of proxy conflicts rather than direct war. The nuclear balance of terror would last until 1991.' },
  { id: 'e6', year: 1950, type: 'conflict', title: 'Korean War Begins', era: 'postwar',
    detail: 'North Korea\'s June 25, 1950 invasion of South Korea tested whether the Truman Doctrine had teeth. The UN (with the USSR boycotting the Security Council) authorized a US-led intervention. China\'s entry in October transformed the conflict, killing ~36,000 Americans and ~180,000 Chinese. The armistice (1953) left the peninsula divided at the 38th parallel — exactly where it started. Korea cemented the US commitment to forward military basing in Asia and established the pattern of proxy war that defined Cold War conflict.' },
  { id: 'e7', year: 1955, type: 'trade', title: 'Bandung Conference', era: 'postwar',
    detail: 'Twenty-nine African and Asian nations met in Bandung, Indonesia to assert a "Third Way" outside Cold War blocs. Led by Nehru, Nasser, Sukarno, and Zhou Enlai, the conference birthed the Non-Aligned Movement and challenged the binary of US-Soviet competition. Economically, it foreshadowed demands for commodity price stability and development finance — themes that would resurface in the 1970s\' NIEO (New International Economic Order) proposals.' },

  // --- COLD WAR PEAK ---
  { id: 'e8', year: 1956, type: 'conflict', title: 'Suez Crisis', era: 'coldwar',
    detail: 'Egypt\'s Nasser nationalized the Suez Canal in July 1956, triggering a secret Anglo-French-Israeli military operation. Eisenhower\'s furious opposition — he threatened to crash the British pound if they didn\'t withdraw — marked the definitive end of British imperial power and the transition to full American hegemony over Western strategic interests. The episode also pushed Egypt toward the Soviet sphere. Control of shipping chokepoints (Suez, Hormuz, Malacca) has defined trade-security interaction ever since.' },
  { id: 'e9', year: 1957, type: 'trade', title: 'Treaty of Rome / EEC', era: 'coldwar',
    detail: 'The Treaty of Rome created the European Economic Community, beginning Western Europe\'s long march toward economic integration. The initial six (France, West Germany, Italy, Benelux) eliminated internal tariffs and created a common external tariff. For the US, the EEC was simultaneously welcome (prosperous allies are stable allies) and threatening (a rival trade bloc). The EEC/EU\'s evolution from free trade zone to political union is one of the defining institutional experiments of the post-war era.' },
  { id: 'e10', year: 1961, type: 'conflict', title: 'Bay of Pigs / Berlin Wall', era: 'coldwar',
    detail: 'Two defining Cold War failures in 1961: the CIA-backed Cuban exile invasion collapsed in April, humiliating Kennedy and cementing Castro\'s alignment with the USSR. In August, East Germany built the Berlin Wall — the most literal symbol of the Iron Curtain. The wall prevented the hemorrhage of East German skilled workers (3M had fled West since 1945) but became the defining image of communist failure. These events raised Cold War tensions to their highest point, directly preceding the Cuban Missile Crisis.' },
  { id: 'e11', year: 1962, type: 'conflict', title: 'Cuban Missile Crisis', era: 'coldwar',
    detail: '13 days in October 1962 brought the world closest to nuclear war. Soviet placement of missiles in Cuba (responding to US missiles in Turkey) triggered a naval blockade and back-channel negotiation. The resolution — Soviets remove Cuban missiles, US pledges no invasion of Cuba and quietly removes Turkish missiles — established the informal rules of nuclear crisis management: direct communication (the "hotline" followed), face-saving exits, and mutual restraint. The crisis paradoxically stabilized Cold War competition by showing both sides the unacceptable cost of escalation.' },
  { id: 'e12', year: 1965, type: 'conflict', title: 'Vietnam Escalation', era: 'coldwar',
    detail: 'President Johnson\'s decision to deploy 500,000+ US troops to Vietnam after the Gulf of Tonkin resolution was the pivotal commitment of the Cold War era. The war\'s economic cost ($738B in 2020 dollars) contributed directly to the collapse of the Bretton Woods gold standard as LBJ refused to raise taxes to fund both the Great Society and the war. The military failure destroyed confidence in American strategic judgment, weakened the dollar, and opened political space for Nixon\'s opening to China.' },
  { id: 'e13', year: 1971, type: 'trade', title: 'Nixon Ends Gold Standard', era: 'coldwar',
    detail: 'On August 15, 1971, Nixon unilaterally ended the Bretton Woods system by suspending dollar-gold convertibility. Facing a run on US gold reserves (foreign governments, especially France under de Gaulle, were converting dollars to gold), Nixon chose to preserve policy autonomy over international monetary order. The resulting "Nixon Shock" moved the world to floating exchange rates and redefined the dollar\'s role: now backed not by gold but by US military power and the fact that oil was priced in dollars — the petrodollar system.' },

  // --- DÉTENTE & SHOCKS ---
  { id: 'e14', year: 1972, type: 'conflict', title: 'Nixon Opens China', era: 'detente',
    detail: 'Nixon\'s February 1972 visit to China — unimaginable four years earlier — exploited the Sino-Soviet split to triangulate US strategic advantage. The Shanghai Communiqué acknowledged Taiwan\'s ambiguous status without forcing a crisis. The opening had cascading effects: China eventually entered global supply chains (especially post-1978 under Deng), the USSR faced a two-front strategic problem, and Taiwan became the world\'s most dangerous potential flashpoint. The trip exemplifies how personal leadership and strategic vision can reshape global order.' },
  { id: 'e15', year: 1973, type: 'trade', title: 'OPEC Oil Embargo', era: 'detente',
    detail: 'Arab OPEC members\' October 1973 embargo (retaliating for US support of Israel in the Yom Kippur War) quadrupled oil prices and revealed the structural vulnerability of oil-dependent Western economies. The US responded by negotiating the petrodollar system: Saudi Arabia would price oil in dollars and recycle petrodollars into US Treasuries; the US would guarantee Saudi security. This bargain, formalized by Kissinger and Treasury Secretary Simon, entrenched dollar hegemony through commodity pricing and shaped Middle East policy for 50 years.' },
  { id: 'e16', year: 1975, type: 'conflict', title: 'Fall of Saigon', era: 'detente',
    detail: 'North Vietnamese forces captured Saigon on April 30, 1975, completing the communist reunification of Vietnam. For American grand strategy, the defeat triggered deep introspection: the "Vietnam syndrome" constrained military interventionism for a decade, the War Powers Act (1973) reasserted Congressional authority, and the CIA was subjected to the Church Committee hearings. Strategic credibility questions would haunt US policy — how to deter Soviet adventurism while avoiding another quagmire? The answer came in the form of proxy arming of anti-Soviet forces globally.' },
  { id: 'e17', year: 1978, type: 'trade', title: 'Deng\'s Reform & Opening', era: 'detente',
    detail: 'Deng Xiaoping\'s ascendance in 1978 and the launch of "reform and opening up" (改革开放) began one of history\'s most dramatic economic transformations. Special Economic Zones (Shenzhen was farmland in 1979, a megacity by 1990), foreign investment liberalization, and gradualist privatization of agriculture lifted ~800 million people from poverty over 40 years. For global trade, it created the world\'s largest manufacturing base. For geopolitics, it created the central challenge of the 21st century: integrating a non-liberal great power into a liberal international order.' },
  { id: 'e18', year: 1979, type: 'conflict', title: 'Iranian Revolution / Soviet-Afghan War', era: 'detente',
    detail: 'Two 1979 events reshaped the Middle East and Central Asia for generations. The Iranian Revolution replaced the Shah (a key US security partner and oil supplier) with a Shi\'a theocracy hostile to America — stranding 66 hostages for 444 days and triggering a US tilt toward Iraq. The Soviet invasion of Afghanistan in December launched a CIA/ISI-backed mujahideen insurgency that bled the Red Army for 10 years. The Afghan blowback — jihadist networks, US-armed militants — would mature into al-Qaeda and the post-9/11 era.' },
  { id: 'e19', year: 1980, type: 'trade', title: 'Volcker Shock & Reagan Revolution', era: 'detente',
    detail: 'Fed Chair Volcker\'s decision to raise rates to 20% to break the inflation spiral of the 1970s caused a brutal recession (unemployment peaked at 10.8%) but restored dollar credibility. Reagan\'s supply-side tax cuts, deregulation, and defense buildup restructured the American economy. The combination accelerated the dismantling of industrial unions, kicked off three decades of financialization, and — crucially — created the large trade deficits that would eventually become the defining tension of the global trading system.' },
  { id: 'e20', year: 1985, type: 'trade', title: 'Plaza Accord', era: 'detente',
    detail: 'The Plaza Accord (September 1985) saw the G5 nations agree to depreciate the dollar vs the yen and deutschmark to correct US trade imbalances. The yen doubled against the dollar within two years, making Japanese exports expensive and triggering Japan\'s asset bubble (nikkei peaked in 1989 before a 30-year bear market). The Accord showed the limits of coordinated currency management — the cure created its own crises. It foreshadowed similar debates about the RMB\'s undervaluation in the 2000s-2010s.' },
  { id: 'e21', year: 1989, type: 'conflict', title: 'Berlin Wall Falls / Tiananmen', era: 'detente',
    detail: 'November 9, 1989: the Berlin Wall fell, initiating the collapse of European communist states. June 4, 1989: China\'s PLA crushed pro-democracy protesters in Tiananmen Square. The divergence is crucial — the USSR allowed political liberalization that led to its dissolution; China suppressed it and maintained party control over a market economy. These two events define the central question of the next 35 years: can authoritarian capitalism succeed long-term, and how does the liberal order respond to it?' },

  // --- UNIPOLAR MOMENT ---
  { id: 'e22', year: 1991, type: 'conflict', title: 'Gulf War / USSR Dissolves', era: 'unipolar',
    detail: 'The Gulf War (Jan-Feb 1991) showcased overwhelming US conventional military dominance — 100 hours of ground combat after 6 weeks of air war expelled Iraq from Kuwait. The victory seemed to validate the "Revolution in Military Affairs" thesis. Then in December 1991, the Soviet Union formally dissolved, leaving the United States as the sole superpower. Francis Fukuyama\'s "End of History" thesis captured the triumphalist mood. The structural question — what does a unipolar hegemon do? — would be answered problematically over the next 20 years.' },
  { id: 'e23', year: 1994, type: 'trade', title: 'NAFTA & WTO', era: 'unipolar',
    detail: 'NAFTA (January 1, 1994) integrated the US, Canadian, and Mexican economies, accelerating manufacturing migration to Mexico. On the same day, the Zapatista uprising in Chiapas signaled rural Mexico\'s rejection. Then the Uruguay Round created the WTO (January 1995), replacing GATT with a binding dispute resolution mechanism. These two agreements accelerated globalization\'s winners (consumers, multinationals) and losers (manufacturing workers in rich countries) — the political backlash to which arrived 20 years later in the form of Trump and Brexit.' },
  { id: 'e24', year: 1997, type: 'trade', title: 'Asian Financial Crisis', era: 'unipolar',
    detail: 'The 1997-98 Asian Financial Crisis began in Thailand (baht devaluation) and cascaded to Korea, Indonesia, Malaysia, and Russia. IMF rescue packages came with harsh austerity conditions (the "Washington Consensus"), which enraged recipient governments and their populations. The crisis had two lasting effects: Asian nations accumulated massive dollar reserves to avoid future IMF dependency (the origin of China\'s $3T+ reserves), and it discredited the IMF/World Bank orthodoxy, opening space for alternative development models including China\'s state-directed approach.' },
  { id: 'e25', year: 2001, type: 'conflict', title: '9/11 & the War on Terror', era: 'unipolar',
    detail: 'The September 11 attacks killed 2,977 people and triggered the longest wars in American history. The invasion of Afghanistan (Oct 2001) to destroy al-Qaeda\'s sanctuary was followed by the invasion of Iraq (Mar 2003) on the false premise of WMD. Total post-9/11 war costs: $8 trillion (Watson Institute). The wars failed to produce stable liberal democracies, discredited American military power, and generated strategic vacuum that Iran, China, and Russia exploited. The greatest geopolitical gift to China in the post-Cold War era was the 20 years America spent distracted in the Middle East.' },
  { id: 'e26', year: 2001, type: 'trade', title: 'China Joins WTO', era: 'unipolar',
    detail: 'China\'s WTO accession in December 2001 was the pivotal trade event of the 21st century. The "China shock" research (Autor, Dorn, Hanson) documented the loss of 2-2.5 million US manufacturing jobs between 2001-2007. But the macro picture is more complex: China\'s integration reduced consumer goods inflation, funded US deficits by buying Treasuries, and lifted hundreds of millions out of poverty. The strategic miscalculation was the belief that WTO membership would lead China toward liberal democracy — a projection that has proved definitively wrong.' },
  { id: 'e27', year: 2008, type: 'trade', title: 'Global Financial Crisis', era: 'unipolar',
    detail: 'The 2008 Global Financial Crisis, triggered by the collapse of the US mortgage-backed securities market, was the most severe financial shock since 1929. The Federal Reserve\'s emergency response (TARP, QE1-3, near-zero rates) stabilized the system but required unprecedented intervention. China\'s $586B stimulus package helped stabilize global demand. The crisis delegitimized financial deregulation orthodoxy, deepened inequality (asset prices recovered; wages stagnated), and created the populist soil for Brexit, Trump, and the rise of economic nationalism globally.' },

  // --- MULTIPOLAR FRACTURE ---
  { id: 'e28', year: 2013, type: 'trade', title: 'Belt & Road Initiative', era: 'multipolar',
    detail: 'Xi Jinping announced the Belt and Road Initiative (BRI) in September 2013 — the most ambitious infrastructure investment program in history, eventually touching 150+ countries and $1T+ in lending. BRI is simultaneously economic (creating markets and supply chains for Chinese goods), strategic (building military-capable ports from Djibouti to Pakistan), and diplomatic (creating debt-leverage relationships). Critics call it "debt-trap diplomacy"; proponents call it development that the West refused to fund. The truth is that it is a comprehensive bid for economic and strategic influence projection.' },
  { id: 'e29', year: 2014, type: 'conflict', title: 'Russia Annexes Crimea', era: 'multipolar',
    detail: 'Russia\'s annexation of Crimea in March 2014 and support for Donbas separatists marked the end of the post-Cold War European security order. The EU/US response — economic sanctions — showed both the power and limits of financial coercion: Russia\'s economy contracted but did not collapse, and Putin\'s domestic approval surged. The conflict accelerated European defense spending discussions (though action lagged) and previewed the full-scale invasion of 2022. It also revealed the central tension: economic interdependence (European gas dependency) as both a weapon and a vulnerability.' },
  { id: 'e30', year: 2016, type: 'conflict', title: 'Brexit & Trump Election', era: 'multipolar',
    detail: 'June 23, 2016: UK votes to leave the EU (52-48). November 8, 2016: Donald Trump wins the US presidency. Both votes expressed the accumulated grievances of globalization\'s losers: deindustrialized regions, cultural anxiety about immigration, and distrust of technocratic elites. Brexit cost the UK ~4% of GDP by most estimates and created an Irish border problem that still festers. Trump\'s "America First" policy attacked the institutional architecture the US had built since 1945 — NATO, WTO, and multilateral agreements — testing whether the liberal order could survive its architect\'s departure.' },
  { id: 'e31', year: 2018, type: 'trade', title: 'US-China Trade War', era: 'multipolar',
    detail: 'Trump\'s imposition of tariffs on $550B of Chinese goods (China retaliated on $185B of US goods) formally launched the US-China economic confrontation that had been building for 15 years. Beyond tariffs, the conflict extended to technology (Huawei blacklisting, semiconductor export controls), investment screening (CFIUS expansion), and supply chain decoupling rhetoric. The Biden administration kept most Trump tariffs and extended controls — revealing bipartisan consensus that managed interdependence with China was a strategic mistake.' },
  { id: 'e32', year: 2022, type: 'conflict', title: 'Russia Invades Ukraine', era: 'multipolar',
    detail: 'Russia\'s full-scale invasion of Ukraine on February 24, 2022 produced the largest land war in Europe since 1945. The Western response — $175B+ in military/economic aid, unprecedented financial sanctions including central bank asset freezes — tested the weaponization of the dollar-based financial system. Russia\'s economy proved more resilient than expected (China, India, and Gulf states increased purchases). The war accelerated European energy independence from Russia, NATO expansion (Finland, Sweden), and global ammunition supply chain strain. It also revealed the potential limits of financial sanctions as a coercive tool.' },
  { id: 'e33', year: 2023, type: 'trade', title: 'IRA & Chips Act / AI Race', era: 'multipolar',
    detail: 'The US Inflation Reduction Act (2022) and CHIPS and Science Act (2022) represented the largest industrial policy intervention in American history — $369B for clean energy and $52B for semiconductor manufacturing. Combined with export controls on advanced chips to China (Oct 2022), these measures marked a decisive turn from free-market orthodoxy to state-directed industrial competition. Simultaneously, the ChatGPT launch (Nov 2022) kicked off an AI race with profound implications for productivity, labor markets, and military competition that are still unfolding.' },
];

export const FIGURES = [
  // Post-War
  { id: 'f1', name: 'Harry Truman', role: 'US President', years: [1945, 1953], era: 'postwar',
    color: '#4a6fa5', side: 'West',
    detail: 'Truman presided over the most consequential foreign policy decisions of the post-war founding: atomic bombing of Japan, Marshall Plan, NATO, containment doctrine, and Korean intervention. His choices locked in the architecture that persisted for 80 years. A former senator with no foreign policy experience, he relied heavily on Dean Acheson and George Marshall — the team that produced the most strategically coherent US foreign policy of the 20th century.' },
  { id: 'f2', name: 'George Marshall', role: 'SecState / SecDef', years: [1947, 1951], era: 'postwar',
    color: '#4a6fa5', side: 'West',
    detail: 'Marshall\'s combination of military genius (architect of Allied victory in WWII as Army Chief of Staff) and diplomatic vision (Marshall Plan) is without parallel in American history. The Marshall Plan ($13B) was not charity but strategy: rebuild European markets, prevent communist electoral victories in France and Italy, and create US export markets. Eisenhower said Marshall was the greatest man he ever knew.' },
  { id: 'f3', name: 'Stalin', role: 'Soviet Premier', years: [1945, 1953], era: 'postwar',
    color: '#8b1a1a', side: 'East',
    detail: 'Stalin\'s post-war strategy was defensive in motivation (he feared a rearmed Germany) but expansionist in effect — imposing Soviet-dominated governments across Eastern Europe and supporting communist insurgencies in Greece, China, and Korea. His death in 1953 created power struggle and eventually led to Khrushchev\'s de-Stalinization, slightly relaxing Cold War tensions. Stalin\'s paranoia killed millions of Soviet citizens even while he built the USSR into a superpower.' },
  { id: 'f4', name: 'Dean Acheson', role: 'Sec. of State', years: [1949, 1953], era: 'postwar',
    color: '#4a6fa5', side: 'West',
    detail: 'Acheson was the principal architect of containment policy as Secretary of State under Truman. He helped create NATO, guided the Korean War policy, and shaped the diplomatic framework that would persist through the Cold War. His memoir "Present at the Creation" remains the best insider account of the post-war order\'s construction. His clarity about American interests — "In the beginning was the act" — made him the quintessential realist statesman.' },

  // Cold War Peak
  { id: 'f5', name: 'Eisenhower', role: 'US President', years: [1953, 1961], era: 'coldwar',
    color: '#4a6fa5', side: 'West',
    detail: 'Eisenhower\'s "New Look" strategy substituted nuclear deterrence for expensive conventional forces, freeing budget for domestic investment. He ended the Korean War, resisted military pressure to intervene in Vietnam, and in his farewell address warned of the "military-industrial complex" — the most prescient exit speech of any president. He also covertly overthrew Mossadegh in Iran (1953) and Arbenz in Guatemala (1954), planting seeds of future crises.' },
  { id: 'f6', name: 'Khrushchev', role: 'Soviet Premier', years: [1953, 1964], era: 'coldwar',
    color: '#8b1a1a', side: 'East',
    detail: 'Khrushchev\'s "Secret Speech" denouncing Stalin\'s crimes (1956) partially liberated the Soviet system, but his erratic temperament created crises (Berlin, Cuba) that nearly ended civilization. He backed down in the Cuban Missile Crisis when confronted with US naval power — a humiliation that led to his ouster and the USSR\'s resolve to never again be at such a strategic disadvantage, fueling the arms buildup that nearly bankrupted the Soviet economy.' },
  { id: 'f7', name: 'JFK', role: 'US President', years: [1961, 1963], era: 'coldwar',
    color: '#4a6fa5', side: 'West',
    detail: 'Kennedy\'s 1000 days produced the most dangerous moment of the Cold War (Cuban Missile Crisis) and its most successful resolution. His management of the crisis — resisting military pressure for airstrikes, running back-channel communications through his brother — established the template for nuclear crisis management. His assassination created a Vietnam decision vacuum; Johnson, lacking Kennedy\'s confidence to withdraw, escalated.' },
  { id: 'f8', name: 'LBJ', role: 'US President', years: [1963, 1969], era: 'coldwar',
    color: '#4a6fa5', side: 'West',
    detail: 'Lyndon Johnson\'s Great Society domestic program was arguably the most transformative since the New Deal: Medicare, Medicaid, Voting Rights Act, Civil Rights Act. But his Vietnam escalation destroyed his presidency and his coalition. He refused to raise taxes to fund both guns and butter, triggering the inflation that eventually killed Bretton Woods. The tragic paradox of LBJ: his domestic ambition required foreign policy restraint he couldn\'t muster.' },
  { id: 'f9', name: 'Mao Zedong', role: 'PRC Chairman', years: [1949, 1976], era: 'coldwar',
    color: '#8b1a1a', side: 'East',
    detail: 'Mao unified China after a century of humiliation (1949) but his subsequent campaigns — the Great Leap Forward (1958-62, 15-55M dead from famine) and Cultural Revolution (1966-76, 500K-2M killed) — caused catastrophic self-inflicted damage. His strategic genius in splitting from the USSR and playing the US against Russia (Nixon visit) was real, as was his ruthlessness. His death in 1976 freed Deng Xiaoping to reverse course and begin China\'s actual rise.' },

  // Détente
  { id: 'f10', name: 'Nixon / Kissinger', role: 'President / NSA', years: [1969, 1977], era: 'detente',
    color: '#4a6fa5', side: 'West',
    detail: 'The Nixon-Kissinger partnership produced the most consequential strategic repositioning in American Cold War history: opening China, détente with the USSR, ending Vietnam (at enormous cost), and — less celebrated — the petrodollar system and support for authoritarian allies globally. Kissinger\'s realpolitik prioritized stability over democracy, enabling the Pinochet coup in Chile (1973) and Indonesian massacres. The China opening alone reshuffled the strategic board entirely.' },
  { id: 'f11', name: 'Deng Xiaoping', role: 'PRC Paramount Leader', years: [1978, 1992], era: 'detente',
    color: '#c9a050', side: 'China',
    detail: 'Deng\'s "reform and opening" unleashed the most rapid economic growth in human history. His pragmatism ("it doesn\'t matter if a cat is black or white, so long as it catches mice") replaced Maoist ideology with market mechanisms while maintaining party political control. He authorized the Tiananmen massacre to preserve political stability, believing economic freedom required political order. His successors — Jiang, Hu, Xi — built on his foundation while gradually reversing his political openness.' },
  { id: 'f12', name: 'Reagan', role: 'US President', years: [1981, 1989], era: 'detente',
    color: '#4a6fa5', side: 'West',
    detail: 'Reagan\'s defense buildup ($2T over 8 years), SDI program, and Reagan Doctrine of arming anti-communist insurgencies (Afghanistan, Nicaragua, Angola, Cambodia) accelerated Soviet overextension. Whether he "won" the Cold War or merely outlasted it is debated, but the USSR collapsed under Gorbachev while Reagan\'s framework was still operating. His supply-side economics and deregulation reshaped US domestic political economy in ways still contested 40 years later.' },
  { id: 'f13', name: 'Gorbachev', role: 'Soviet Premier', years: [1985, 1991], era: 'detente',
    color: '#8b1a1a', side: 'East',
    detail: 'Gorbachev\'s Glasnost (openness) and Perestroika (restructuring) were intended to save the Soviet system by reforming it — instead, they unraveled it. His refusal to use force to suppress Eastern European revolutions (unlike previous Soviet interventions in Hungary 1956, Czechoslovakia 1968) allowed the peaceful dissolution of the Warsaw Pact. Whether this was strategic vision or loss of control is the central question of his legacy. He died in 2022, living long enough to see Russia attempt to reverse the post-Cold War order.' },

  // Unipolar
  { id: 'f14', name: 'George H.W. Bush', role: 'US President', years: [1989, 1993], era: 'unipolar',
    color: '#4a6fa5', side: 'West',
    detail: 'Bush 41 managed the most consequential period of post-war geopolitics with extraordinary skill: German reunification, the Gulf War coalition (34 nations), and the Soviet dissolution — all without triggering the great-power conflicts that history would have predicted. His "New World Order" speech articulated a vision of multilateral governance that his successors failed to sustain. Widely considered the most competent foreign policy president of the post-war era.' },
  { id: 'f15', name: 'Clinton', role: 'US President', years: [1993, 2001], era: 'unipolar',
    detail: 'Clinton\'s presidency coincided with the "unipolar moment" — unchallenged US power, the dotcom boom, and globalization\'s acceleration. NAFTA, WTO, China\'s MFN status, and NATO expansion (without adequate planning for Russia\'s reaction) were his major trade/security moves. The decision not to intervene in Rwanda (800K dead) and the botched Somalia intervention (Black Hawk Down) shaped his caution on military force. His impeachment and political divisions foreshadowed the polarization to come.',
    color: '#4a6fa5', side: 'West', years: [1993, 2001], era: 'unipolar' },
  { id: 'f16', name: 'George W. Bush', role: 'US President', years: [2001, 2009], era: 'unipolar',
    color: '#4a6fa5', side: 'West',
    detail: 'Bush 43\'s presidency was defined by 9/11 and the consequent "War on Terror." The Afghanistan and Iraq invasions consumed American strategic attention, treasure ($8T), and credibility for 20 years. The Iraq War — sold on false WMD premises — ranks among the costliest strategic miscalculations in American history. Simultaneously, his administration oversaw the 2008 financial crisis (deregulation legacy), China\'s WTO accession integration, and the beginning of US-China strategic competition.' },
  { id: 'f17', name: 'Jiang Zemin', role: 'PRC President', years: [1993, 2003], era: 'unipolar',
    color: '#c9a050', side: 'China',
    detail: 'Jiang navigated China through the sensitive post-Tiananmen period, presiding over explosive economic growth while suppressing political dissent (Falun Gong crackdown, 1999). He secured China\'s WTO membership (2001) — the single most consequential trade event of his era. His "three represents" theory expanded party legitimacy beyond workers to include entrepreneurs, beginning the party\'s evolution from class-based to nationalist legitimacy.' },

  // Multipolar
  { id: 'f18', name: 'Obama', role: 'US President', years: [2009, 2017], era: 'multipolar',
    color: '#4a6fa5', side: 'West',
    detail: 'Obama\'s presidency confronted the aftermath of the financial crisis, managed the Arab Spring, killed bin Laden, negotiated the Iran nuclear deal (JCPOA), and announced the "Pivot to Asia" — all while domestic polarization deepened. His restraint in Syria (red line not enforced) damaged US credibility; his TPP trade agreement (designed to counter China) was abandoned by his successor. The Obama era represents the end of unipolar confidence: the US could no longer shape events unilaterally.' },
  { id: 'f19', name: 'Xi Jinping', role: 'PRC President', years: [2013, 2026], era: 'multipolar',
    color: '#c9a050', side: 'China',
    detail: 'Xi has concentrated more power than any Chinese leader since Mao, abolishing term limits (2018) and conducting sweeping anti-corruption campaigns that consolidated his personal authority. His "China Dream" nationalism, BRI infrastructure projection, military modernization (especially naval), South China Sea island-building, and economic coercion of dissenting neighbors represent the most significant revisionist challenge to the post-war order. The Taiwan question — will he attempt reunification by force? — is the most consequential strategic uncertainty of the 21st century.' },
  { id: 'f20', name: 'Putin', role: 'Russian President', years: [2000, 2026], era: 'multipolar',
    color: '#8b1a1a', side: 'East',
    detail: 'Putin\'s two-decade project to reverse Russia\'s post-Soviet humiliation culminated in the full-scale invasion of Ukraine (2022). His strategy has been to exploit Western energy dependency, information warfare, election interference, and military force to restore Russian great-power status. The Ukraine invasion has produced the opposite of his intended strategic outcome — NATO is stronger, Ukraine is seeking EU membership, and Russia is economically isolated — but the war continues with no clear end. His historical significance may ultimately rest on whether he triggers or avoids nuclear escalation.' },
  { id: 'f21', name: 'Angela Merkel', role: 'German Chancellor', years: [2005, 2021], era: 'multipolar',
    color: '#2a5c45', side: 'West',
    detail: 'Merkel governed Germany for 16 years through the financial crisis, Eurozone debt crisis, refugee crisis (1M Syrian refugees admitted in 2015), and COVID. Her strategic error — deepening German energy dependency on Russian gas (Nord Stream 2) — has been widely criticized in retrospect. But her steady, consensus-based leadership stabilized Europe through multiple crises and her scientific background (PhD in quantum chemistry) shaped a uniquely evidence-based governance style. Germany\'s post-Merkel geopolitical awakening (Zeitenwende) is still unfolding.' },
  { id: 'f22', name: 'Trump', role: 'US President', years: [2017, 2021], era: 'multipolar',
    color: '#4a6fa5', side: 'West',
    detail: 'Trump\'s first term disrupted the post-war institutional architecture: withdrew from TPP, Paris Agreement, Iran nuclear deal, and questioned NATO\'s Article 5 commitment. His tariff war with China (and allies) was the most aggressive US trade intervention since Smoot-Hawley. Whether his disruption was strategic (forcing NATO burden-sharing, confronting China) or destructive (weakening alliances) is the central debate of his legacy. His return to office in 2025 has re-opened all these questions at higher intensity.' },
];

export const THREADS = [
  {
    id: 'dollar', title: 'Dollar Hegemony Arc', color: '#c9a050',
    summary: 'The dollar\'s role as global reserve currency — won at Bretton Woods (1944), maintained through the petrodollar deal (1974), tested by the euro and Chinese RMB, and now challenged by sanctions weaponization.',
    events: ['e1', 'e13', 'e15', 'e24', 'e32', 'e33'],
  },
  {
    id: 'china', title: 'China\'s Rise', color: '#e07b2a',
    summary: 'From Mao\'s revolution (1949) through Deng\'s market reforms (1978), WTO accession (2001), BRI (2013), and Xi\'s assertive nationalism — the central geopolitical story of the 21st century.',
    events: ['e14', 'e17', 'e21', 'e26', 'e28', 'e31', 'e33'],
  },
  {
    id: 'oil', title: 'Oil as Power', color: '#e0bc6e',
    summary: 'From the 1973 embargo through the petrodollar system, Gulf Wars, shale revolution, and the energy transition — how hydrocarbon control has structured military alliances, trade balances, and strategic rivalries.',
    events: ['e13', 'e15', 'e18', 'e22', 'e29', 'e32'],
  },
  {
    id: 'afghan', title: 'The Afghan Thread', color: '#8b4513',
    summary: 'The CIA\'s Soviet-era mujahideen arming created al-Qaeda, which drove 9/11, which produced a 20-year war that ended where it started. The clearest case study in strategic blowback in modern history.',
    events: ['e18', 'e25'],
  },
  {
    id: 'globalization', title: 'Globalization Arc', color: '#2a5c45',
    summary: 'From GATT (1947) through the WTO/NAFTA era of hyperglobalization (1990s-2000s), to the China shock backlash, Trump tariffs, and COVID supply chain disruptions — the rise and fracture of the free-trade consensus.',
    events: ['e3', 'e9', 'e23', 'e24', 'e26', 'e27', 'e30', 'e31'],
  },
];
